POST http://localhost:3030/detailed-plan HTTP/1.1
Content-Type: application/json

{
  "days": 3,
  "destination": "Islamabad",
  "interests": ["fine dining", "cuisine"],
  "budget": "medium",
  "travelMode": "public transport"
}
